# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b0275e220d9f46efa8992a222254b3ba3c0aac57161dd2cbc1b4aa290e95f67563a17b64b1548401f59aef65c0491fe567cf2939fd4c3122537efe6da7f2f6a

test:
  secret_key_base: 743b331a00ceef8b6ddee429c4d1e7bca13021dfba39637237d7fe62accd746b44e23fa48aa81eff9eedb391c1ca0a4fa1b1d68c6386123f4a7ec83ec77386ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
